Keep getting the TypeError: BrandonsMacBook:PythonPractice bgoss$ python ex45.py
        Wow! It's really dark in here.
        As you slowly walk through the maze, you notice something.
        A door! Will you enter or pass this door?

> enter
Traceback (most recent call last):
  File "ex45.py", line 183, in <module>
    a_game.play()
  File "ex45.py", line 27, in play
    next_scene_name = current_scene.enter()
TypeError: enter() takes exactly 2 arguments (1 given)

I feel like in the final lines where I do the calls i need to somehow
pass an argument to include the weapons but I'm not sure how. Been stuck
on this program for a few weeks now.